vcl 4.1;

# The most statistics a tenant may have.
static var s0: INT stat;
static var s1: INT stat;
static var s2: INT stat;
static var s3: INT stat;
static var s4: INT stat;
static var s5: INT stat;
static var s6: INT stat;
static var s7: INT stat;
static var s8: INT stat;
static var s9: INT stat;
static var s10: INT stat;
static var s11: INT stat;
static var s12: INT stat;
static var s13: INT stat;
static var s14: INT stat;
static var s15: INT stat;
static var s16: INT stat;
static var s17: INT stat;
static var s18: INT stat;
static var s19: INT stat;
static var s20: INT stat;
static var s21: INT stat;
static var s22: INT stat;
static var s23: INT stat;
static var s24: INT stat;
static var s25: INT stat;
static var s26: INT stat;
static var s27: INT stat;
static var s28: INT stat;
static var s29: INT stat;
static var s30: INT stat;
static var s31: INT stat;
static var s32: INT stat;
static var s33: INT stat;
static var s34: INT stat;
static var s35: INT stat;
static var s36: INT stat;
static var s37: INT stat;
static var s38: INT stat;
static var s39: INT stat;
static var s40: INT stat;
static var s41: INT stat;
static var s42: INT stat;
static var s43: INT stat;
static var s44: INT stat;
static var s45: INT stat;
static var s46: INT stat;
static var s47: INT stat;
static var s48: INT stat;
static var s49: INT stat;
static var s50: INT stat;
static var s51: INT stat;
static var s52: INT stat;
static var s53: INT stat;
static var s54: INT stat;
static var s55: INT stat;
static var s56: INT stat;
static var s57: INT stat;
static var s58: INT stat;
static var s59: INT stat;
static var s60: INT stat;
static var s61: INT stat;
static var s62: INT stat;
static var s63: INT stat;

sub vcl_recv {
    set var.s0 += 1;
    return (synth(200));
}
