#pragma once
#define SYSCALL_BASE 500

#define ECALL_FAIL (SYSCALL_BASE+0)
#define ECALL_ASSERT_FAIL (SYSCALL_BASE+1)
#define ECALL_PRINT (SYSCALL_BASE+2)
#define ECALL_WRITE  ECALL_PRINT
#define ECALL_LOG (SYSCALL_BASE+3)
#define ECALL_BREAKPOINT (SYSCALL_BASE+4)
#define ECALL_SIGNAL (SYSCALL_BASE+5)
#define ECALL_IS_STORAGE (SYSCALL_BASE+6)
#define ECALL_REMOTECALL (SYSCALL_BASE+7)
#define ECALL_REMSTRCALL (SYSCALL_BASE+8)

#define ECALL_REGISTER_CB (SYSCALL_BASE+9)
#define ECALL_SET_DECISION (SYSCALL_BASE+10)
#define ECALL_SET_BACKEND (SYSCALL_BASE+11)
#define ECALL_BACKEND_DECISION (SYSCALL_BASE+12)
#define ECALL_BAN (SYSCALL_BASE+13)
#define ECALL_HASH_DATA (SYSCALL_BASE+14)
#define ECALL_PURGE (SYSCALL_BASE+15)
#define ECALL_SYNTH (SYSCALL_BASE+16)
#define ECALL_CACHEABLE (SYSCALL_BASE+17)
#define ECALL_TTL (SYSCALL_BASE+18)

#define ECALL_FOREACH_FIELD (SYSCALL_BASE+19)
#define ECALL_FIELD_GET (SYSCALL_BASE+20)
#define ECALL_FIELD_RETRIEVE (SYSCALL_BASE+21)
#define ECALL_FIELD_APPEND (SYSCALL_BASE+22)
#define ECALL_FIELD_SET (SYSCALL_BASE+23)
#define ECALL_FIELD_COPY (SYSCALL_BASE+24)
#define ECALL_FIELD_UNSET (SYSCALL_BASE+25)

#define ECALL_HTTP_ROLLBACK (SYSCALL_BASE+26)
#define ECALL_HTTP_COPY (SYSCALL_BASE+27)
#define ECALL_HTTP_SET_STATUS (SYSCALL_BASE+28)
#define ECALL_HTTP_UNSET_RE (SYSCALL_BASE+29)
#define ECALL_HTTP_FIND (SYSCALL_BASE+30)

#define ECALL_REGEX_COMPILE (SYSCALL_BASE+31)
#define ECALL_REGEX_MATCH (SYSCALL_BASE+32)
#define ECALL_REGEX_SUBST (SYSCALL_BASE+33)
#define ECALL_REGSUB_HDR (SYSCALL_BASE+34)
#define ECALL_REGEX_FREE (SYSCALL_BASE+35)

#define ECALL_SHA256 (SYSCALL_BASE+36)
#define ECALL_FIELD_RETRIEVE_STR (SYSCALL_BASE+37)
#define ECALL_BASE64_DECODE (SYSCALL_BASE + 38)
#define ECALL_REGISTER_FUNC (SYSCALL_BASE + 39)

#define ECALL_LAST (SYSCALL_BASE+40)
